apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: flask-test
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test
spec:
  selector:
    matchLabels:
      app: flask-test
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-test
    spec:
      containers:
      - name: flask-test
        image: flask-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

        