FROM ubuntu:18.04

RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev

WORKDIR /app/

COPY ./rabbitmq /app

# ENTRYPOINT [ "python3" ]

CMD [ "python3", "consumer_question.py" ]
