version: '3.8'

services:
  
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  worker:
    build: 
      context: .
      dockerfile: dockerfile.worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: dockerfile.server
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
    
  consumer:
    build: consumer
    volumes:
      - ./consumer:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - worker